apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e4d32swp8-python 
  janus-idp.io/tekton: e4d32swp8-python
  backstage.io/kubernetes-id: e4d32swp8-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e4d32swp8-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml