apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e4d32swp8-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/e4d32swp8-python-gitops